"""CEFR study-hour norms — re-exported from app_config (ADR-002)."""

from services.app_config import (
    DEFAULT_PRACTICE_DAYS_PER_WEEK,
    DEFAULT_TUTOR_LESSON_MINUTES,
    DEFAULT_TUTOR_LESSONS_PER_WEEK,
    HOURS_PER_CEFR_LEVEL,
    PLAN_DISCLAIMER,
    SCENARIO_BASED_COEFFICIENT,
    STUCK_LOAD_MIN_CATEGORIES,
    STUCK_LOAD_MULTIPLIER,
)

__all__ = [
    "HOURS_PER_CEFR_LEVEL",
    "SCENARIO_BASED_COEFFICIENT",
    "DEFAULT_TUTOR_LESSONS_PER_WEEK",
    "DEFAULT_TUTOR_LESSON_MINUTES",
    "DEFAULT_PRACTICE_DAYS_PER_WEEK",
    "PLAN_DISCLAIMER",
    "STUCK_LOAD_MULTIPLIER",
    "STUCK_LOAD_MIN_CATEGORIES",
]
